### ISSUE TITLE
Switching to RDT and back to normal FPS camera

### ISSUE THREAD

**Issue by GonnaFlyMethod** [bbbscarter/GodotRuntimeDebugTools#3] opened 2024-08-24 13:01 UTC
Hi, the addon looks interesting, I wonder what is the way to switch between default Character camera and Freelook camera from the addon? So, for example, I run the scene, and I have Godot's default FPS camera that is designed for gameplay, and then in some moment I want to switch to Freelook(debug) camera in order to observe the game world. For now, when I start the game from the editor, I immediately getting a Freelook camera without opportunity to switch to the player's view.

It would be nice to switch back and fourth between these cameras

**Comment by bbbscarter** [comment] 2024-08-24 14:03
Ah, I think this is a regression in the situation where the scene has no defined 'current' camera; because the debug camera is the first in the scene, it's erroneously picked as the 'current' camera.

I've just pushed a fix to github - let me know if it fixes it for you and I'll push it up to the asset library.

**Comment by GonnaFlyMethod** [comment] 2024-08-25 10:26
Hey, the problem is on my side: I haven't set up check box "Current" on my main Character camera 3D. After that, switching between Character main camera and Debug 3D camera back and fourth went smooth(I've checked on both versions: v1.1.0 and v1.1.1).  May be, let's add a note to README for future godoters, what do u think?


____

**Proposal for enhancement:**
The only thing I've discovered is that when switching back from Debug3D camera to Main Character camera,  the mouse input mode is not preserved: I'm testing the game in windowed mode, when I start it the mouse is enteirely hidden: 

```csharp
Input.MouseMode = Input.MouseModeEnum.Captured;
```

then, I do ALT + TAB to quickly navigate to godot and hit RDT (3D Debug camera). After that,  I'm switching back to Character camera (FPS camera) by unchecking 3D Debug camera in RDT, and the mouse is visible, and because of it, when I want to rotate a character, the character rotates as long as the mouse cursor is presented in the game window, if the cursor exits from the window frame, then the character stop rotating. My proposal is to preserve the mouse input mode when switching back to the game camera.  By the way, in order not to ALT+ TAB each time, may be shortcuts can be introduced in game process?

**Comment by bbbscarter** [comment] 2024-08-25 20:31
> Hey, the problem is on my side: I haven't set up check box "Current" on my main Character camera 3D. After that, switching between Character main camera and Debug 3D camera back and fourth went smooth(I've checked on both versions: v1.1.0 and v1.1.1). May be, let's add a note to README for future godoters, what do u think?

Yup, that's another way of fixing it, certainly, but my preference is that users don't have to change their projects if possible. The fix I've pushed will hopefully fix it for everyone, without any local changes needed.

> Proposal for enhancement:
Thanks, I can look into that! Would you be able to propose this in a new issue, so I can keep this one focused on the original issue you reported?

> By the way, in order not to ALT+ TAB each time, may be shortcuts can be introduced in game process?
There is currently a hidden option to do this - F12. My intention is to make that configurable in the future, which is why it hasn't been documented yet. :)

**Comment by GonnaFlyMethod** [comment] 2024-08-26 07:54
Hey, by the way with 1.1.1 before switching Character camera to "Current", when I was hitting "Play" the default camera was the one that was placed in the center of the map[it looks like this camera was added by debug tools].

**Comment by bbbscarter** [comment] 2024-08-26 12:54
Yup, that would be my expectation - it would have erroneously picked up the debug camera as the 'current' camera, and the debug camera is initally at (0,0,0).

This should be fixed in 1.1.2 (pending review in the asset library), or current [github head.](https://github.com/bbbscarter/GodotRuntimeDebugTools/commit/3b2fdfb9748cdcf3a75e4ff5d05a7121d6bd4462)

**Comment by GonnaFlyMethod** [comment] 2024-08-26 14:44
I've created a separated [issue](https://github.com/bbbscarter/GodotRuntimeDebugTools/issues/4) with more details about preserving mouse input mode, by the way, I would like to contribute to the project, do you consider new contributors now 🙂?

**Comment by bbbscarter** [comment] 2024-08-26 16:57
I'm certainly happy to consider pull-requests!

**Comment by GonnaFlyMethod** [comment] 2024-08-27 16:27
hey, cool. I think, I'll to check out the codebase on this weekend and let you know how it goes. I would like to work on my [proposal](https://github.com/bbbscarter/GodotRuntimeDebugTools/issues/4#issuecomment-2310389094)

**Comment by bbbscarter** [comment] 2024-09-26 16:56
Fixed in #5 

Thanks!

**Closed** 2024-09-26 16:55 UTC

**Comment by GonnaFlyMethod** [comment] 2024-09-26 18:10
Hey, btw, will you create a new version with the fix included?

**Comment by bbbscarter** [comment] 2024-09-26 18:14
Ah yes, I was a bit slow returning to this.

It should be live as of earlier today (v 1.1.3).

**Comment by bbbscarter** [comment] 2024-09-26 19:26
Sure! I'm sometimes on Discord - also email/Google chat/Mastodon work for
me!

**Comment by GonnaFlyMethod** [comment] 2024-09-27 07:12
Let's connect on discord? My nickname is gonnaflymethod. The same avatar as in github

**Comment by bbbscarter** [comment] 2024-09-27 19:36
Sure, will do. I'm @bbbscarter everywhere as well.
